### ISSUE TITLE
Resize array error in timeseries monitor

### ISSUE THREAD

**Issue by astroclark** [gwpy/dataviewer#3]
Attempting to set up a timeseries monitor for ISI-GND_STS_ITMY_Z_BLRMS_30M_100M with the following configuration:

[monitor]
type = timeseries
duration = 100
interval = 5

yields the resize error below.    The error goes away if duration=interval.

(gwpysoft)phys24162:examples admin$ gwdv ./ISI-GND_STS_ITMY_Z_BLRMS_30M_100M.ini 
[GWDV monitor 1126474629]     INFO: Monitor ready to start
    Use the run() method of the monitor to execute
[GWDV monitor 1126474638] CRITICAL: Exception occured, figure will be left open, but will not update
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 1290, in _on_timer
    ret = func(_args, *_kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/animation.py", line 925, in _step
    still_going = Animation._step(self, *args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/animation.py", line 784, in _step
    self._draw_next_frame(framedata, self._blit)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/animation.py", line 803, in _draw_next_frame
    self._draw_frame(framedata)
  File "/opt/gwpysoft/lib/python2.7/site-packages/dataviewer/data.py", line 134, in _draw_frame
    self.refresh()
  File "/opt/gwpysoft/lib/python2.7/site-packages/dataviewer/timeseries.py", line 145, in refresh
    ts.append(t2, pad=self.buffer.pad, gap=self.buffer.gap)
  File "/opt/gwpysoft/lib/python2.7/site-packages/gwpy/data/series.py", line 402, in append
    self.resize(s, refcheck=False)
ValueError: cannot resize this array: it does not own its data

**Comment by mikelovskij** [comment]
Hi, there seems to be an issue when ts is generated (at line 141 of timeseries.py), the keyword copy=True doesn't seem to do its work. You can find a workaround to this issue in the branch 'gwpy-workarounds'.

**Comment by duncanmmacleod** [comment]
@mikelovskij: was this bug fixed in one of your pull requests? If so, please confirm and close.

**Comment by mikelovskij** [comment]
Yes, however it was more a workaround than a real fix, since the issue seems to have origin in gwpy, where the TimeSeries(line.get_ydata(), times=line.get_xdata(), copy=True) does not seem to respect the copy=True keyword, requiring the execution of an additional .copy() method in order to allow the resizing of the generated timeseries without incurring in the exception "ValueError: cannot resize this array: it does not own its data"

**Comment by duncanmmacleod** [comment]
Ok, since it no longer presents in dataviewer, I will close here. If another user posts a bug report for gwpy, I will build a fix around that.
